name: TEST_GITHUB
on:
  workflow_dispatch:

permissions:
  contents: write

env:

  #TW_VERSION: 
  
  # change value from:

  # A) choosing right manifest:
  # 1) recovery type: 
     # to build twrp, add: twrp
     # to build shrp, add: shrp
     # to build pbrp, add: pbrp
  RTYPE: twrp
  # 2) manifest is required choose the compatible its depend on your current android version.
  MANIFEST: https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git
  # 3) manifest branch same thing it depend on your current android
  BRANCH: twrp-7.1

  # B) Information about your device:
  # 1) every device tree use main file called twrp_/omni_****.mk use the name between .mk and omni_/twrp_ keyword
  DEVICE: INTEX_ELYT_DUAL
  # 2) device tree link
  DT_LINK: https://github.com/twrpdtgen/android_device_intex_INTEX_ELYT_DUAL
  # 3) device tree branch which you want to build
    # if your repo doesnt have a one branch not renamed use: main
  DT_BR: INTEX_ELYT_DUAL_V19_INDIAN
  # 4) device manufacturer please you the one which used on device.mk or BoardConfig.mk 
  MANUFACTURER: intex
  # 5) target build. depend on what you have on you phone. recovery partition: recovery or recovery in boot partition: boot
  TARGET: recovery
  # 6) build type eng (recommended) , user (dont use it), userdebug (this too)
  BTYPE: eng
  # 7) Twrp type omni or twrp may depend on main file omni_/twrp_****.mk
  OT: omni
  # end dont edit anything after this comment
  
  # C) these part and what under dont edit it
  IMAGE: image
  SYM: _

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Init the System
         uses: actions/checkout@master
                               
       - name: remove pkg and setting repo
         run: |
            pwd
            ls
            echo TWRP_VERSION=$(wget -qO- https://github.com/TeamWin/android_bootable_recovery/blob/android-9.0/variables.h | grep 'TW_MAIN_VERSION_STR' | sed -n "s/.*<span class=\"pl-s\"><span class=\"pl-pds\">&quot;\(.*\)<span class=\"pl-pds\">&quot;<\/span><\/span>.*/\1/p" | sed 's/<.*>//g')-0-$DEVICE >> $GITHUB_ENV

       - name: Show Env Info
         run: |
            echo $TWRP_VERSION

       - name: Release recovery
         uses: softprops/action-gh-release@v1
         env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
          tag_name: ${{ env.TWRP_VERSION }}#${{ github.run_id }}
          name: recovery for ${{ env.DEVICE }}
          
